### PR TITLE
Team #3 - login1 and searchproducts - SQLi fix

### PR DESCRIPTION
**Pull request by oferzern**
Fixing both login1.php and searchproducts.php pages for manual SQLi through web access using regex to validate the user's input.

[Team #3 - SQL Challenge.docx](https://github.com/redhat-beyond/sqlinjection-training-app/files/7574640/Team.3.-.SQL.Challenge.docx)

### CODE REVIEW

**Comment by OrAsaf** [comment]
Make sure to add your writeup to the PR as the instructions suggested.

**Comment by oferzern** [comment]
Hi @1Oreo 
I've attached the write-up for our SQLi flow as a file.
Do you want it to be as plain text instead?

**Comment by OrAsaf** [comment]
Oh OK I missed that it was attached to the PR in a comment. Having it as a docx is fine, I was just looking for it as part of the PR itself (looked at files changed). This can also work the way you attached it so disregard my previous comment.

**Comment by OrAsaf** [comment]
Only team to go for whitelisting which is the way to go when it comes to payloads! Great work!

**Pull request closed without merging**
